# Generated by Django 3.2 on 2022-04-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrames', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
